name: docker-builds

on:
  workflow_dispatch:
  pull_request:
    paths:
      - .circleci/docker/**
      - .github/workflows/docker-builds.yml
  schedule:
    - cron: 1 3 * * 3

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

env:
  ALPINE_IMAGE: 308535385114.dkr.ecr.us-east-1.amazonaws.com/tool/alpine
  AWS_DEFAULT_REGION: us-east-1

jobs:
  docker-build:
    runs-on: [self-hosted, linux.2xlarge]
    timeout-minutes: 240
    strategy:
      matrix:
        include:
          - docker-image-name: pytorch-linux-bionic-cuda10.2-cudnn7-py3.9-gcc7
          - docker-image-name: pytorch-linux-bionic-cuda11.5-cudnn8-py3-gcc7
          - docker-image-name: pytorch-linux-bionic-py3.7-clang9
          - docker-image-name: pytorch-linux-bionic-rocm4.3.1-py3.7
          - docker-image-name: pytorch-linux-bionic-rocm4.5-py3.7
          - docker-image-name: pytorch-linux-xenial-cuda10.2-cudnn7-py3-gcc7
          - docker-image-name: pytorch-linux-xenial-cuda11.3-cudnn8-py3-gcc7
          - docker-image-name: pytorch-linux-xenial-py3-clang5-android-ndk-r19c
          - docker-image-name: pytorch-linux-xenial-py3-clang5-asan
          - docker-image-name: pytorch-linux-xenial-py3-clang7-asan
          - docker-image-name: pytorch-linux-xenial-py3-clang7-onnx
          - docker-image-name: pytorch-linux-xenial-py3.7-gcc5.4
          - docker-image-name: pytorch-linux-xenial-py3.7-gcc7
    env:
      DOCKER_IMAGE_BASE: 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/${{ matrix.docker-image-name }}
    steps:
      - name: Clean workspace
        shell: bash
        run: |
          echo "${GITHUB_WORKSPACE}"
          sudo rm -rf "${GITHUB_WORKSPACE}"
          mkdir "${GITHUB_WORKSPACE}"

      - name: Checkout PyTorch
        uses: zhouzhuojie/checkout@05b13c9a0d21f08f6d5e64a1d5042246d13619d9
        with:
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
          # deep clone, to allow use of git merge-base
          fetch-depth: 0
          submodules: recursive

      - name: Setup Linux
        uses: ./.github/actions/setup-linux
        with:
          github-secret: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        id: build-docker-image
        uses: ./.github/actions/calculate-docker-image
        with:
          docker-image-name: ${{ matrix.docker-image-name }}
          always-rebuild: true

      - name: Pull Docker image
        env:
          DOCKER_IMAGE: ${{ steps.build-docker-image.outputs.docker-image }}
        run: |
          retry () { "$@"  || (sleep 1 && "$@") || (sleep 2 && "$@") }
          retry docker pull "${DOCKER_IMAGE}"

      - name: Chown workspace
        if: always()
        run: |
          # Ensure the working directory gets chowned back to the current user
          docker run --rm -v "$(pwd)":/v -w /v "${ALPINE_IMAGE}" chown -R "$(id -u):$(id -g)" .

      - name: Hold runner for 2 hours or until ssh sessions have drained
        # Always hold for active ssh sessions
        if: always()
        run: .github/scripts/wait_for_ssh_to_drain.sh

      - name: Kill containers, clean up images
        if: always()
        run: |
          # ignore expansion of "docker ps -q" since it could be empty
          # shellcheck disable=SC2046
          docker stop $(docker ps -q) || true
          # Prune all of the docker images
          docker system prune -af
